name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  checks: write

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Cargo format check
        run: cargo fmt --all -- --check

      - name: Cargo build
        run: cargo build --verbose

      - name: Cargo clippy check
        run: cargo clippy --all-targets -- -D warnings

      - name: Cargo test
        run: cargo test --verbose

  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Generate Cargo.lock
        run: |
          cargo generate-lockfile
          cargo update -p time
      
      - name: Install cargo-audit
        uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignore: |
            RUSTSEC-2026-0009
            RUSTSEC-2025-0057
            RUSTSEC-2025-0119
            RUSTSEC-2024-0436
            RUSTSEC-2026-0002
